# from intro

A number of studies have explored how flexible the learned behaviours are in contextual cuing. For example, a number of studies have shown that moving the target to a new position within the display will abolish the established CC effect [@makovski2011; @manginelli2009]. Notably, @zellin2013 explored the remapping of target positions over a longer training period, observing that with extended training, new associations will form for these new target positions, though the effects are limited to targets that appear closer to those that are initially trained. This suggests that any relocation effect is driven strongly by a generalisation of the pre-existing associations. Furthermore, strong contextual cuing effects were observed for the initially trained targets in a final "return phase" at the end of the experiment. All of these results point towards CC constituting a fairly inflexible behaviour that is activated somewhat automatically during search.

More direct examination of the role of top-down control processes on CC comes from @luque2017b (Experiment 3). They used a task in which participants were initially given a standard CC experiment (search for a T amongst Ls), before then being told in a second phase that the target would appear in two designated positions along the horizontal mid-line of the screen. Participants were given an explicit instruction to search in these two locations for a new target (a Y); in this phase participants engaged in a new search task requiring controlled attention to specified locations. Yet the underlying configuration of repeated distractors was still present, as was the original target, which appeared in its trained location for that configuration. Luque et al. found that the acquired knowledge of the configurations did not affect performance in this second phase: responses to the new target were comparable when the old target was pointed in either the same or opposite direction to the new target, suggesting that there was no detectable processing of the old target [see also @luque2021]. The suggestion is that contextual cuing can be controlled in the presence of a top-down instruction to search in a new location - search is not automatic in nature in the CC task.

One potential issue with the studies presented by Luque and colleagues [@luque2017b; @luque2021] is that participants are instructed to engage in a new search process for a new target object: participants initially search for a T and are later instructed to search for a Y. The role of a prior target template is important for visual search [@vickery2005; @vo2012], and object identities appear to play an important role in the contextual cuing effect [@makovski2017; @makovski2018]. While it is unclear how dependent CC is on the identity of the target, it is possible that distractor-target associations may well be sensitive to target identity and to the goals of the participant. For this reason, the current study assesses the impact of top-down instruction on CC when participants maintain the same task goal of searching for a single target identity within the display.

The overarching aim of the current study is to explore the interaction between controlled (top-down) attentional processes and the pattern of search behaviour established by the repeated configurations. Specifically we seek to understand whether repeated configurations continue to guide attention even when participants are directed to alter their natural search patterns by the presence of an endogenous cue (an arrow that instructs the participant to direct attention in a specific direction). The experiments explore both the performance aspect of CC in terms of whether it continues to guide behaviour once an endogenous cue is introduced, and also whether the development of the search behaviour is impeded when trained concurrently with the endogenous cue.

# from Experiment 2 intro and discussion

We can also consider the predictions from an associative learning perspective: so called "cue-competition" effects have been examined previously in contextual cuing. @endo2004 trained participants with a contextual cuing task composed of distractor location configurations and repeating distractor identities. Their experiments suggested that the stronger configural (spatial) cue out-competed the cue provided by the distractor identities. Similarly, @kunar2014 found that when colour cues and configural cues both predicted the target location, configural cues were dominant and tended to overshadow the weaker colour cue. @beesley2012 looked at the cue-interaction effects *within* a configuration of distractors. Participants were first trained with half a configuration of repeating distractors that predicted the target (8 out of 16 distractors). In a later stage these distractors were paired with a new half-configuration, such that the whole configuration now predicted the same target location. In contrast to the predictions of the vast majority of models of contingency learning, learning about these new predictive distractors was facilitated, rather than impaired in this second phase (relative to a control condition). Thus, @beesley2012 found that cue-competition was not observed within a configuration of equally predictive distractors. Together these studies suggest that the spatial configuration serves as a strong cue for the target and will out-compete non-configural cues for access to the learning mechanism. The dominance of the configuration in these situations may therefore lead to the prediction that the endogenous cue would not "block" the learning of the configuration in the current task.

The lack of competition effects seen in Experiment 2 are at odds with some findings in the CC literature [i.e., @endo2004; @kunar2014], where competition has been seen by more dominant or salient features of the displays. Instead, the findings point towards a more automatic nature to contextual cuing, whereby associations form ubiquitously, so long as they receive the focus of attention at some point within the search process [e.g., @beesley2012].

# from intro to Experiment 3

Existing data from studies of contextual cuing has pointed towards a localised learning effect for repeated configurations, with those distractors closest to the target being preferentially weighted in the learning process over those located further from the target. For example, @olson2002 trained participants with three sets of repeating configurations that differed in terms of which distractors repeated across trials. For one set, the entire global context (all of the distractors) repeated, while for the other two sets only the short-range (those close to the target) or the long-range distractors (those far from the target) repeated across trials. They found no difference between the CC effect in the short-range and global configurations, while the CC effect was not significant for the long-range context. Similar results have been shown by @brady2007 which led to the development of the spatial constraints model of contextual cuing, in which distractor-target associations occurring in close proximal space are weighted more heavily in the learning process (over those occurring across greater spatial distance).
